random_seed: 42

# getDataframe
train_size: 0.667
test_size: 0.333
csv_dir: './'
save_csv: False

output_classes: 20
embed_layer: 'top_conv'
gradcam_image_num: 20

tsne:
  n_components: 2
  learning_rate: 'auto'
  random_state: 42 
  init: 'pca'
  perplexity: 3
