random_seed: 42

# getDataframe
train_size: 0
test_size: 0
csv_dir: './'
use_csv: False

num_classes: 108
output_classes: 20
embed_layer: 'top_conv'
gradcam_image_num: 6

tsne:
  n_components: 2
  learning_rate: 'auto'
  random_state: 42 
  init: 'pca'
  perplexity: 3
